language: c
sudo: false
dist: xenial
script: make
addons:
  apt:
    packages:
        - gcc-arm-none-eabi
        - linux-libc-dev
        - glibc-source
        - libc6
        - libc6-dev
        - gcc
        - build-essential
